DROP TABLE REVIEWLOG;
DROP SEQUENCE REVIEWLOG_SEQ;

CREATE SEQUENCE reviewlog_seq START WITH 1;

CREATE TABLE REVIEWLOG (
    Review_ScrapeID     NUMBER(10)      NOT NULL,
    Month               VARCHAR2(10)     NOT NULL,
    ScrapeDate          DATE
);

ALTER TABLE REVIEWLOG ADD (
    CONSTRAINT Review_ScrapeID PRIMARY KEY (Review_ScrapeID));
    
CREATE OR REPLACE TRIGGER reviewlog_trg
BEFORE INSERT ON REVIEWLOG
FOR EACH ROW

BEGIN
    SELECT reviewlog_seq.NEXTVAL
    INTO :new.Review_ScrapeID
    FROM Dual;
END;