CREATE SEQUENCE bandlog_seq START WITH 1;

CREATE TABLE BANDLOG (
    Band_ScrapeID   NUMBER(10)  NOT NULL,
    Letter          VARCHAR2(5) NOT NULL,
    ScrapeDate      DATE
);

ALTER TABLE BANDLOG ADD (
    CONSTRAINT Band_ScrapeID PRIMARY KEY (Band_ScrapeID));
    
CREATE OR REPLACE TRIGGER bandlog_trg
BEFORE INSERT ON BANDLOG
FOR EACH ROW

BEGIN
    SELECT bandlog_seq.NEXTVAL
    INTO :new.Band_ScrapeID
    FROM Dual;
END;