DROP TABLE DISCOGLOG;
DROP SEQUENCE DISCOGLOG_SEQ;

CREATE SEQUENCE discoglog_seq START WITH 1;

CREATE TABLE DISCOGLOG (
    Discog_ScrapeID   NUMBER(10)  NOT NULL,
    BandID          NUMBER(10) NOT NULL,
    ScrapeDate      DATE
);

ALTER TABLE DISCOGLOG ADD (
    CONSTRAINT Discog_ScrapeID PRIMARY KEY (Discog_ScrapeID));
    
CREATE OR REPLACE TRIGGER discoglog_trg
BEFORE INSERT ON DISCOGLOG
FOR EACH ROW

BEGIN
    SELECT discoglog_seq.NEXTVAL
    INTO :new.Discog_ScrapeID
    FROM Dual;
END;