ALTER TABLE metalarchives.Band 
	MODIFY COLUMN BandName VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	MODIFY COLUMN BandLink VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    MODIFY COLUMN BandStatus VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    MODIFY COLUMN Country VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    MODIFY COLUMN Genre VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
;